### ISSUE TITLE
Can I use v8::Isolate::GetCurrent()->GetCpuProfiler()->StartProfiling in a new thread?

### ISSUE THREAD

**Issue by hyj1991** [node-inspector/v8-profiler#100]
Beacuse when node main thread blocked by some resason(like some regular expression
greedy matching and so on...)，I want to write an addon using v8-profiler in a new thread(by uv_thread_create or uv_queue_work) , But I try it and always return "Segmentation fault: 11" when executing "v8::Isolate::GetCurrent()->GetCpuProfiler()->StartProfiling" in a new thread, How can I solve this? 
Thanks.

**Comment by paulrutter** [comment]
You could try https://www.npmjs.com/package/node-oom-heapdump, which creates snapshots from a separate process.
