### ISSUE TITLE
Create heapdump when out of memory occurs

### ISSUE THREAD

**Issue by paulrutter** [node-inspector/v8-profiler#109]
I've been using the v8-profiler module for quite some time now, and it often helps me to pinpoint memory issues.
One feature i really miss; when a nodejs process actually goes out of memory (FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory), i would like a heapdump of that specific moment.

Java has a flag for this, "-XX:+HeapDumpOnOutOfMemoryError". Does either this module or Node.js itself have equivalent functionality?
If not, is it even remotely possible to add this kind of functionality?

Thanks in advance for your response.

**Comment by paulrutter** [comment]
I just read the [following article](https://v8project.blogspot.nl/2017/02/one-small-step-for-chrome-one-giant.html), which shows a feature that pauses the debugger when an out-of-memory crash is about to occur. Is this something the v8-profiler can hook into?
Maybe @bnoordhuis knows something about this?

**Comment by bnoordhuis** [comment]
I haven't checked how it's implemented but I expect the inspector monitors the JS heap and calls `isolate->IncreaseHeapLimitForDebugging()` right before it's full.

One way to do monitoring is with `isolate->AddGCEpilogueCallback()` and checking `isolate->GetHeapStatistics()` in the callback.

**Comment by paulrutter** [comment]
So, if i understand correctly, you think this is something that can be fixed in v8-inspector?
That would be a great feature to have, do you agree?

For me this would be a great help, as we run 500+ nodejs processes in Docker containers (memory limited by supplying --max-old-space-size=x) which can run out of memory depending on which custom code is being run. If a heapdump could be automatically created right before an OoM occurs, that would really help us to pinpoint memory issues.

**Comment by paulrutter** [comment]
For future reference; i've made code that monitors GC events (using node-gcstats) and checks the used heapsize when a Full GC has occured. Then the heapsize exceeds a configurable threshold, a heapdump is created (by using v8-profiler).
This doesn't involve increasing the heap like you suggest @bnoordhuis, since there is no JS API for that (afaik). I going to test if this is somewhat useful next weeks.

```
// node modules
var fs = require('fs');
var path = require('path');

// external modules
var gcStats = new require('gc-stats')();
var profiler = require('v8-profiler');

// private
var filePath = path.resolve(__dirname, "./heapdump.heapsnapshot");
var heapdumpCreated = false;
var OOM_DETECTION_CONFIG = {
  maxHeapSize: 80, // this should be the value that is passed to the nodejs process in --max_old_space_size=x
  threshold: 90 // the threshold percentage for making a heapdump. When the heap is filled above this threshold after a Full GC, it creates a heapdump
};

// listen to GC events
gcStats.on('stats', function(stats) {
  // gctype 2 is a Full GC (Mark/Sweep/Compact)
  if (stats.gctype === 2 && !heapdumpCreated) {
    var heapSizeUsedPercentage = ((parseInt(stats.after.usedHeapSize) / 1000000) / OOM_DETECTION_CONFIG.maxHeapSize) * 100;
    if (heapSizeUsedPercentage > OOM_DETECTION_CONFIG.threshold) {
      heapdumpCreated = true;

      // this is a full GC and the used heap size is using more than x% of the assigned heap space limit
      console.warn("OoM is imminent: Full GC (Mark/Sweep/Compact) complete and still more than %s% (%s%) of the heap is used. Creating heapdump now. GC stats: ", OOM_DETECTION_CONFIG.threshold, Math.round(heapSizeUsedPercentage), stats);
       
      // create heapdump now
      var snapshot = profiler.takeSnapshot();
      snapshot.export().pipe(fs.createWriteStream(filePath))
      .on('error', function(err){
        snapshot.delete();
        console.error("Creating heapdump failed", err);
      })
      .on('finish', function() {
        snapshot.delete();
        console.error("Heapdump created.");
      });
    }
  }
});

```

Any thoughts on this?

**Comment by paulrutter** [comment]
I finally have a working solution and decided to create a separate module for it.
It doesn't involve increasing the heaplimit though, but leverages the DevTools protocol to create heapdumps from another process.

See https://github.com/blueconic/node-oom-heapdump if your interested.

**Comment by paulrutter** [comment]
For future reference: there is a V8 hook that can be used for this called SetOOMErrorHandler. It can be used in a native addon. See https://v8docs.nodesource.com/node-8.9/d5/dda/classv8_1_1_isolate.html#a08fd4087f39c33b4ac1c20ad953ce4e3.

The latest version of node-oom-heapdump is using this feature now.
