### ISSUE TITLE
CPU-profile not showing in Chrome performance tab

### ISSUE THREAD

**Issue by nanom1t** [node-inspector/v8-profiler#116]
Hi,

I'm trying to optimize my Node.js app performance with v8-profiles. I've installed npm package and generated few profile files with next code:
```
        var fs = require('fs');
        var profileName = 'get-users-top_' + moment().format('YYYYMMDD-HH:mm:ss');
        var profiler = require('v8-profiler');
        profiler.startProfiling(profileName, true);
....
                                profile.export()
                                    .pipe(fs.createWriteStream(configs.APP_ROOT + '/../' + profileName + '.json'))
                                    .on('finish', function() {
                                        profile.delete();
                                    });
```
The code works good and I get files. However, when I'm trying to visualize these files in Chrome (Performance tab -> Load profile -> Select file), the result window is blank.
![screen shot 2017-07-21 at 9 22 58 am](https://user-images.githubusercontent.com/6481192/28451494-4c97004c-6df6-11e7-9d75-2131250411e8.png)
Chrome: Version 59.0.3071.115 (Official Build) (64-bit)

What I'm doing wrong? Please help.

**Comment by nanom1t** [comment]
Is this repo dead?

**Comment by hyj1991** [comment]
@nanom1t 

Hi, only files with extensions **.cpuprofile** can be loaded. And now cpu-profiling tool moved as follow:

 **More tools->Javascript Profiler**

![image](https://user-images.githubusercontent.com/19908330/28506439-1428f354-705e-11e7-8b68-f10ebfc5ce29.png)

**Comment by azaslavsky** [comment]
I was having massive trouble with this problem in 2018 using Chrome 65.  It seems like the old CPU profiler that this package relies on has been sunsetted in the newer versions of chrome.  Installing the version of Chromium mentioned in this issue (available here for Mac: https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac/464636/) and loading the profile there solved the problem for me.
