### ISSUE TITLE
can I export profile information to text instead of node-inspector

### ISSUE THREAD

**Issue by guileen** [node-inspector/v8-profiler#12]
can I export profile information to text instead of node-inspector, maybe in the log file.

**Comment by Andre-487** [comment]
+1

**Comment by eljefedelrodeodeljefe** [comment]
Although this seems a little off-scope for this module I like the idea also. But rather JSON-stream. Is broadening the API actually wanted @3y3 .

**Comment by eljefedelrodeodeljefe** [comment]
This would be solved by #58

**Comment by 3y3** [comment]
Look at `export` methods
