### ISSUE TITLE
How to analyze the result of v8-profiler?

### ISSUE THREAD

**Issue by nobody4t** [node-inspector/v8-profiler#125]
I got the example code in the readme. I produced the *.json file.
But how can I analyze it? It is unreadable.

**Comment by nobody4t** [comment]
I have produced a json file when stoping profiling. But I have no idea how to read this properly.

**Comment by izotos** [comment]
In Chrome (65.0):
 -  Navigate to `chrome://inspect`
 - Click `Open dedicated DevTools for Node`
 - Select the _profiler_ tab
 - _Load_ your file (you should need to rename with another extension)

It would be nice to see some examples/suggestions in the README.

**Comment by nobody4t** [comment]
sure. I have found it. thanks.

**Comment by azaslavsky** [comment]
@izotos what did you rename the extension to?  For example, I am currently writing a file called `profile.json`.  What should it be called instead?

**Comment by izotos** [comment]
@azaslavsky I believe it was `.cpuprofile`
