### ISSUE TITLE
node0.8.0 amd64

### ISSUE THREAD

**Issue by madisparn** [node-inspector/v8-profiler#16]
when calling profiler.takeSnapshot I get an error
node: symbol lookup error: xxx/node_modules/v8-profiler/build/Release/profiler.node: undefined symbol: _ZNK2v813HeapGraphNode17GetRetainersCountEv 

tried both master and 3.6.2 branches

**Comment by SkeLLLa** [comment]
Same error on latest node-inspector and v8-profiler with node v0.11.14
