### ISSUE TITLE
Installation failure on ubuntu 10 

### ISSUE THREAD

**Issue by mhdawson** [node-inspector/v8-profiler#48]
It seems like binding.gyp has dos/windows line endings.  This in conjunction with the default level of python in ubuntu 10 results in a failure during install.

Running dos2unix on binding.gyp seems to resolve the issue.

See the following for more details: https://developer.ibm.com/answers/questions/167322/node-gyp-rebuild-fails-during-compile-phase.html#answer-168535

It would be good to fix as ubuntu 10 is used as the default environment for many PaaS environments.

**Comment by 3y3** [comment]
@mdawsonibm , can you please fork last commit `Convert line endings to LF` eaae2c7e45c383d6704e0ccf43fe92439d406460 and submit, that all works correctly.

**Comment by 3y3** [comment]
I added some fixes to v8-profiler and v8-debug. Also I added prebuild binaries for Linux and OSX.
Please try to reinstall node-inspector now.

**Comment by mdawsonibm** [comment]
Sorry I did not get to this earlier.  I just did an npm install in my unbuntu environment and both v8-profiler and v8-debug reported as installing ok.  It reports:

ubuntu@ub10:~/test4$ npm install v8-profiler
|
> v8-profiler@5.2.2 install /home/ubuntu/test4/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

[v8-profiler] Success: "/home/ubuntu/test4/node_modules/v8-profiler/build/profiler/v5.2.2/node-v11-linux-x64/profiler.node" is installed via remote
v8-profiler@5.2.2 node_modules/v8-profiler
âââ nan@1.2.0


I'll ask the original person who reported the issue on dw Answers to validate it works for them (I just tested the install as opposed to using the modules)
