### ISSUE TITLE
Saving snapshot examples

### ISSUE THREAD

**Issue by pflannery** [node-inspector/v8-profiler#56]
When trying to save a heap snapshot that there wasn't any clear examples of how this is done. I ended up digging around the tests to find how to build a heap snapshot.
So it would be great if some save examples were added to the documentation or wiki.

This is what I came up with to save a heap to file. 
```js
var fs = require('fs'),
  profiler = require('v8-profiler');

function saveHeapSnapshot(fileName) {
  var buffer = '',
    snapshot = profiler.takeSnapshot("test");
  snapshot.serialize(
    function iterator(data, length) {
      buffer += data;
    },function complete(){
      fs.writeFileSync(fileName, buffer)
    }
  );
}

saveHeapSnapshot("a.heapsnapshot")
```

Maybe an exposed API to just wrap saving to a file up would be better too.

**Comment by 3y3** [comment]
Look at updated readme
