### ISSUE TITLE
Build error: 'make' failed with exit code: 2

### ISSUE THREAD

**Issue by jlazerus** [node-inspector/v8-profiler#63]
v8-profiler is a dependency for a server app we're trying to install. The installer keeps keeps choking on v8-profiler, like this:

				> v8-profiler@5.2.9 install /var/www/sharelatex/spelling/node_modules/v8-profiler
				> node-pre-gyp install --fallback-to-build

				gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.38"
				gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/sharelatex/spelling/node_modules/v8-profiler/.node-gyp"
				make: Entering directory `/var/www/sharelatex/spelling/node_modules/v8-profiler/build'
				make: *** No rule to make target `../.node-gyp/0.10.38/common.gypi', needed by `Makefile'.  Stop.
				make: Leaving directory `/var/www/sharelatex/spelling/node_modules/v8-profiler/build'
				gyp ERR! build error
				gyp ERR! stack Error: `make` failed with exit code: 2
				gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
				gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
				gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
				gyp ERR! System Linux 2.6.32-504.16.2.el6.x86_64
				gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/var/www/sharelatex/spelling/node_modules/v8-profiler/build/profiler/v5.2.9/node-v11-linux-x64/profiler.node" "--module_name=profiler" "--module_path=/var/www/sharelatex/spelling/node_modules/v8-profiler/build/profiler/v5.2.9/node-v11-linux-x64"
				gyp ERR! cwd /var/www/sharelatex/spelling/node_modules/v8-profiler
				gyp ERR! node -v v0.10.38
				gyp ERR! node-gyp -v v1.0.3
				gyp ERR! not ok
				node-pre-gyp ERR! build error
				node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/var/www/sharelatex/spelling/node_modules/v8-profiler/build/profiler/v5.2.9/node-v11-linux-x64/profiler.node --module_name=profiler --module_path=/var/www/sharelatex/spelling/node_modules/v8-profiler/build/profiler/v5.2.9/node-v11-linux-x64' (1)
				node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/var/www/sharelatex/spelling/node_modules/v8-profiler/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
				node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
				node-pre-gyp ERR! stack     at maybeClose (child_process.js:766:16)
				node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
				node-pre-gyp ERR! System Linux 2.6.32-504.16.2.el6.x86_64
				node-pre-gyp ERR! command "node" "/var/www/sharelatex/spelling/node_modules/v8-profiler/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
				node-pre-gyp ERR! cwd /var/www/sharelatex/spelling/node_modules/v8-profiler
				node-pre-gyp ERR! node -v v0.10.38
				node-pre-gyp ERR! node-pre-gyp -v v0.6.7
				node-pre-gyp ERR! not ok
				Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/var/www/sharelatex/spelling/node_modules/v8-profiler/build/profiler/v5.2.9/node-v11-linux-x64/profiler.node --module_name=profiler --module_path=/var/www/sharelatex/spelling/node_modules/v8-profiler/build/profiler/v5.2.9/node-v11-linux-x64' (1)
				npm ERR! Linux 2.6.32-504.16.2.el6.x86_64
				npm ERR! argv "node" "/usr/bin/npm" "install" "v8-profiler"
				npm ERR! node v0.10.38
				npm ERR! npm  v2.11.0
				npm ERR! code ELIFECYCLE

				npm ERR! v8-profiler@5.2.9 install: `node-pre-gyp install --fallback-to-build`
				npm ERR! Exit status 1
				npm ERR!
				npm ERR! Failed at the v8-profiler@5.2.9 install script 'node-pre-gyp install --fallback-to-build'.
				npm ERR! This is most likely a problem with the v8-profiler package,
				npm ERR! not with npm itself.
				npm ERR! Tell the author that this fails on your system:
				npm ERR!     node-pre-gyp install --fallback-to-build
				npm ERR! You can get their info via:
				npm ERR!     npm owner ls v8-profiler
				npm ERR! There is likely additional logging output above.

				npm ERR! Please include the following file with any support request:
				npm ERR!     /var/www/sharelatex/spelling/node_modules/npm-debug.log

Can this be fixed manually?
~Thanks

**Comment by jlazerus** [comment]
sudo npm install -g node-inspector --unsafe-perm 
solved this problem.

**Comment by hillkim7** [comment]
Hi Jlazerus, thanks it works on Debian 8.

**Comment by jlazerus** [comment]
Yes hillkim7, although this thread was for OS X, I had to use v8-profiler on a Linux. :+1:
