### ISSUE TITLE
Error during installation on Raspberry PI

### ISSUE THREAD

**Issue by ademcaliskan** [node-inspector/v8-profiler#64]
Seem to be an issue in conjunction with raspberry pi model b (rev2).

Please see attached log.

Thanks!

https://gist.githubusercontent.com/ademcaliskan/8654672dac377ef4d422/raw/npm-debug.log

**Comment by 3y3** [comment]
Hm, maybe `sudo npm install -g node-inspector --unsafe-perm` will be helpfull?

**Comment by ademcaliskan** [comment]
Thanks, works like a charm. Remote debugging on Pi is possible now. Woohaa.
