### ISSUE TITLE
Any example of taking heapsnapshot would help

### ISSUE THREAD

**Issue by sandeshhegde83** [node-inspector/v8-profiler#66]
var profiler = require('v8-profiler');
var snapshot = profiler.takeSnapshot('test');

Once I generate snapshot with the above code, how do I store it to a file so that I can load it in chrome devtools?
snapshot.serialize( ...) does not seem to work and the below is also giving error - 
fs.writeFile('/tmp/a.heapsnapshot', JSON.stringify(snapshot));

Any examples to generate the heapsnhot  would be appreciated

**Comment by 3y3** [comment]
Look at latest version 5.3.0
