### ISSUE TITLE
node-pre-gyp needs to be a dep

### ISSUE THREAD

**Issue by bmeck** [node-inspector/v8-profiler#68]
needs to be a dep as it is required for building / is the install script. unsure how to propagate `--nodeddir` to it properly though.

**Comment by 3y3** [comment]
But... `node-pre-gyp` [is dep](https://github.com/node-inspector/v8-profiler/blob/master/package.json#L40). Or I missed something?

**Comment by bmeck** [comment]
bad vendored module did not get pkg json updated. sorry
