### ISSUE TITLE
Upgrade to nan 2.0.5

### ISSUE THREAD

**Issue by thlorenz** [node-inspector/v8-profiler#69]
Just a heads up and a few questions. I'm working on upgrading v8 profiler to work with iojs 3 and nan 2.0.5.

Is any related work going on that I should be aware of?
Do you have any helpful links tips?

Thanks

**Comment by marcominetti** [comment]
Hi @thlorenz, I'm upgrading memwatch to nan 2.0.5 too (it shares some HeapProfiler code), how is going your port?

**Comment by thlorenz** [comment]
It got merged after @rvagg added a few fixes, see #71 
Just forgot to close this issue ;)

**Comment by thlorenz** [comment]
@marcominetti you might find [this script useful](  https://gist.github.com/thlorenz/7e9d8ad15566c99fd116)

**Comment by 3y3** [comment]
This is my mistake. Sorry.
Thank you for fix.
