### ISSUE TITLE
v8-profiler issues on Raspberry PI 2

### ISSUE THREAD

**Issue by victoryred** [node-inspector/v8-profiler#76]
Here’s the machine info etc.
Linux raspberrypi 4.1.6-v7+ #810 SMP PREEMPT Tue Aug 18 15:32:12 BST 2015 armv7l GNU/Linux

root@raspberrypi:~# nodejs -v
v0.10.40
root@raspberrypi:~# npm -v
1.4.28

root@raspberrypi:~# npm install -g node-inspector

> v8-profiler@5.3.1 preinstall /usr/lib/node_modules/node-inspector/node_modules/v8-profiler
>  

> v8-debug@0.5.3 preinstall /usr/lib/node_modules/node-inspector/node_modules/v8-debug
>  

npm WARN optional dep failed, continuing default-browser-id@1.0.2
-
> utf-8-validate@1.2.1 install /usr/lib/node_modules/node-inspector/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.40"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/node-inspector/node_modules/ws/node_modules/utf-8-validate/.node-gyp"
make: Entering directory '/usr/lib/node_modules/node-inspector/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory '/usr/lib/node_modules/node-inspector/node_modules/ws/node_modules/utf-8-validate/build'

> bufferutil@1.2.1 install /usr/lib/node_modules/node-inspector/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.40"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/node-inspector/node_modules/ws/node_modules/bufferutil/.node-gyp"
make: Entering directory '/usr/lib/node_modules/node-inspector/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
make: Leaving directory '/usr/lib/node_modules/node-inspector/node_modules/ws/node_modules/bufferutil/build'

> v8-profiler@5.3.1 install /usr/lib/node_modules/node-inspector/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.40"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/node-inspector/node_modules/v8-profiler/.node-gyp"
make: Entering directory '/usr/lib/node_modules/node-inspector/node_modules/v8-profiler/build'
make: *** No rule to make target '../.node-gyp/0.10.40/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/usr/lib/node_modules/node-inspector/node_modules/v8-profiler/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.1.6-v7+
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.3.1/node-v11-linux-arm/profiler.node" "--module_name=profiler" "--module_path=/usr/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.3.1/node-v11-linux-arm"
gyp ERR! cwd /usr/lib/node_modules/node-inspector/node_modules/v8-profiler
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.3.1/node-v11-linux-arm/profiler.node --module_name=profiler --module_path=/usr/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.3.1/node-v11-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/node-inspector/node_modules/v8-profiler/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:766:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
node-pre-gyp ERR! System Linux 4.1.6-v7+
node-pre-gyp ERR! command "node" "/usr/lib/node_modules/node-inspector/node_modules/v8-profiler/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/node-inspector/node_modules/v8-profiler
node-pre-gyp ERR! node -v v0.10.40
node-pre-gyp ERR! node-pre-gyp -v v0.6.10
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.3.1/node-v11-linux-arm/profiler.node --module_name=profiler --module_path=/usr/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.3.1/node-v11-linux-arm' (1)

> v8-debug@0.5.3 install /usr/lib/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.40"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/node-inspector/node_modules/v8-debug/.node-gyp"
make: Entering directory '/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build'
make: *** No rule to make target '../.node-gyp/0.10.40/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.1.6-v7+
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.3/node-v11-linux-arm/debug.node" "--module_name=debug" "--module_path=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.3/node-v11-linux-arm"
gyp ERR! cwd /usr/lib/node_modules/node-inspector/node_modules/v8-debug
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.3/node-v11-linux-arm/debug.node --module_name=debug --module_path=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.3/node-v11-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/node-inspector/node_modules/v8-debug/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:766:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
node-pre-gyp ERR! System Linux 4.1.6-v7+
node-pre-gyp ERR! command "node" "/usr/lib/node_modules/node-inspector/node_modules/v8-debug/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/node-inspector/node_modules/v8-debug
node-pre-gyp ERR! node -v v0.10.40
node-pre-gyp ERR! node-pre-gyp -v v0.6.10
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.3/node-v11-linux-arm/debug.node --module_name=debug --module_path=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.3/node-v11-linux-arm' (1)

npm ERR! v8-profiler@5.3.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-profiler@5.3.1 install script.
npm ERR! This is most likely a problem with the v8-profiler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-profiler
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.1.6-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "node-inspector"
npm ERR! cwd /root
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
root@raspberrypi:~# npm install -g node-inspector

> v8-profiler@5.3.1 preinstall /usr/lib/node_modules/node-inspector/node_modules/v8-profiler
>  

> v8-debug@0.5.3 preinstall /usr/lib/node_modules/node-inspector/node_modules/v8-debug
>  

npm WARN optional dep failed, continuing default-browser-id@1.0.2
-
> utf-8-validate@1.2.1 install /usr/lib/node_modules/node-inspector/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.40"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/node-inspector/node_modules/ws/node_modules/utf-8-validate/.node-gyp"
make: Entering directory '/usr/lib/node_modules/node-inspector/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory '/usr/lib/node_modules/node-inspector/node_modules/ws/node_modules/utf-8-validate/build'

> bufferutil@1.2.1 install /usr/lib/node_modules/node-inspector/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.40"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/node-inspector/node_modules/ws/node_modules/bufferutil/.node-gyp"
make: Entering directory '/usr/lib/node_modules/node-inspector/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
make: Leaving directory '/usr/lib/node_modules/node-inspector/node_modules/ws/node_modules/bufferutil/build'

> v8-profiler@5.3.1 install /usr/lib/node_modules/node-inspector/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.40"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/node-inspector/node_modules/v8-profiler/.node-gyp"
make: Entering directory '/usr/lib/node_modules/node-inspector/node_modules/v8-profiler/build'
make: *** No rule to make target '../.node-gyp/0.10.40/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/usr/lib/node_modules/node-inspector/node_modules/v8-profiler/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.1.6-v7+
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.3.1/node-v11-linux-arm/profiler.node" "--module_name=profiler" "--module_path=/usr/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.3.1/node-v11-linux-arm"
gyp ERR! cwd /usr/lib/node_modules/node-inspector/node_modules/v8-profiler
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.3.1/node-v11-linux-arm/profiler.node --module_name=profiler --module_path=/usr/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.3.1/node-v11-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/node-inspector/node_modules/v8-profiler/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:766:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
node-pre-gyp ERR! System Linux 4.1.6-v7+
node-pre-gyp ERR! command "node" "/usr/lib/node_modules/node-inspector/node_modules/v8-profiler/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/node-inspector/node_modules/v8-profiler
node-pre-gyp ERR! node -v v0.10.40
node-pre-gyp ERR! node-pre-gyp -v v0.6.10
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.3.1/node-v11-linux-arm/profiler.node --module_name=profiler --module_path=/usr/lib/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.3.1/node-v11-linux-arm' (1)

> v8-debug@0.5.3 install /usr/lib/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.40"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/node-inspector/node_modules/v8-debug/.node-gyp"
make: Entering directory '/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build'
make: *** No rule to make target '../.node-gyp/0.10.40/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.1.6-v7+
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.3/node-v11-linux-arm/debug.node" "--module_name=debug" "--module_path=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.3/node-v11-linux-arm"
gyp ERR! cwd /usr/lib/node_modules/node-inspector/node_modules/v8-debug
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.3/node-v11-linux-arm/debug.node --module_name=debug --module_path=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.3/node-v11-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/node-inspector/node_modules/v8-debug/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:766:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
node-pre-gyp ERR! System Linux 4.1.6-v7+
node-pre-gyp ERR! command "node" "/usr/lib/node_modules/node-inspector/node_modules/v8-debug/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/node-inspector/node_modules/v8-debug
node-pre-gyp ERR! node -v v0.10.40
node-pre-gyp ERR! node-pre-gyp -v v0.6.10
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.3/node-v11-linux-arm/debug.node --module_name=debug --module_path=/usr/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.3/node-v11-linux-arm' (1)

npm ERR! v8-profiler@5.3.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-profiler@5.3.1 install script.
npm ERR! This is most likely a problem with the v8-profiler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-profiler
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.1.6-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "node-inspector"
npm ERR! cwd /root
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by 3y3** [comment]
Use
```
npm install -g node-inspector --unsafe-perm
```

**Comment by victoryred** [comment]
still did not work-



pi@raspberrypi /opt/node/bin $ sudo ./npm install -g node-inspector --unsafe-perm

> v8-profiler@5.3.1 preinstall /opt/node/lib/node_modules/node-inspector/node_modules/v8-profiler
>


> v8-debug@0.5.3 preinstall /opt/node/lib/node_modules/node-inspector/node_modules/v8-debug
>

npm WARN optional dep failed, continuing default-browser-id@1.0.2
|
> utf-8-validate@1.2.1 install /opt/node/lib/node_modules/node-inspector/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

/opt/node/lib/node_modules/npm/bin/node-gyp-bin/node-gyp: 3: /opt/node/lib/node_modules/npm/bin/node-gyp-bin/node-gyp: node: not found

> bufferutil@1.2.1 install /opt/node/lib/node_modules/node-inspector/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

/opt/node/lib/node_modules/npm/bin/node-gyp-bin/node-gyp: 3: /opt/node/lib/node_modules/npm/bin/node-gyp-bin/node-gyp: node: not found
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
npm WARN optional dep failed, continuing bufferutil@1.2.1
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"4.0.0","npm":"2.14.2"})
\
> v8-debug@0.5.3 install /opt/node/lib/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

/usr/bin/env: node: No such file or directory

> v8-profiler@5.3.1 install /opt/node/lib/node_modules/node-inspector/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

/usr/bin/env: node: No such file or directory
npm ERR! Linux 4.1.6-v7+
npm ERR! argv "/opt/node/bin/node" "/opt/node/bin/npm" "install" "-g" "node-inspector" "--unsafe-perm"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! v8-debug@0.5.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the v8-debug@0.5.3 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/node/bin/npm-debug.log










 

Sent from iCloud


On Sep 15, 2015, at 03:22 PM, Yury Puzynya <notifications@github.com> wrote:






Use
npm install -g node-inspector --unsafe-perm

**Comment by victoryred** [comment]
Hi Yuri,



Here's the log file.







 

Sent from iCloud


On Sep 15, 2015, at 03:22 PM, Yury Puzynya <notifications@github.com> wrote:






Use
npm install -g node-inspector --unsafe-perm 

—
Reply to this email directly or view it on GitHub.
info it worked if it ends with ok
verbose cli [ '/usr/bin/nodejs',
verbose cli   '/usr/bin/npm',
verbose cli   '-g',
verbose cli   'install',
verbose cli   'node-inspector' ]
info using npm@1.1.4
info using node@v0.6.19
verbose config file /root/.npmrc
verbose config file /usr/etc/npmrc
verbose config file /usr/share/npm/npmrc
silly exec /usr/bin/nodejs "/usr/share/npm/bin/npm-get-uid-gid.js" "nobody" 1000
silly spawning [ '/usr/bin/nodejs',
silly spawning   [ '/usr/share/npm/bin/npm-get-uid-gid.js', 'nobody', 1000 ],
silly spawning   null ]
silly output from getuid/gid {"uid":65534,"gid":1000}
silly output from getuid/gid 
verbose cache add [ 'node-inspector', null ]
silly cache add: name, spec, args [ undefined, 'node-inspector', [ 'node-inspector', null ] ]
verbose parsed url { pathname: 'node-inspector',
verbose parsed url   path: 'node-inspector',
verbose parsed url   href: 'node-inspector' }
verbose addNamed [ 'node-inspector', '' ]
verbose addNamed [ null, '' ]
silly name, range, hasData [ 'node-inspector', '', false ]
verbose raw, before any munging node-inspector
verbose url resolving [ 'https://registry.npmjs.org/', './node-inspector' ]
verbose url resolved https://registry.npmjs.org/node-inspector
http GET https://registry.npmjs.org/node-inspector
ERR! Error: failed to fetch from registry: node-inspector
ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
ERR!     at Request.emit (events.js:88:20)
ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
ERR!     at ClientRequest.g (events.js:156:14)
ERR!     at ClientRequest.emit (events.js:67:17)
ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1256:7)
ERR! You may report this log at:
ERR!     <http://bugs.debian.org/npm>
ERR! or use
ERR!     reportbug --attach /opt/npm-debug.log npm
ERR! 
ERR! System Linux 4.1.6-v7+
ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "-g" "install" "node-inspector"
ERR! cwd /opt
ERR! node -v v0.6.19
ERR! npm -v 1.1.4
ERR! message failed to fetch from registry: node-inspector
verbose exit [ 1, true ]

**Comment by 3y3** [comment]
The original issue was gone.

I don't have any idea about current error:
```
/opt/node/lib/node_modules/npm/bin/node-gyp-bin/node-gyp: 3:
/opt/node/lib/node_modules/npm/bin/node-gyp-bin/node-gyp: node: not found
```

**Comment by victoryred** [comment]
Hi Yuri,

Up and running thanks for your help.
