### ISSUE TITLE
ReferenceError: selfCounts is not defined v8-profiler.js:32:21

### ISSUE THREAD

**Issue by k1tzu** [node-inspector/v8-profiler#80]
I'm not sure if the issue is so obvious, it just can't be...
v8-profiler.js

=-    var selfCount = selfCounts[key] || 0,
=-        otherCount = otherCounts[key] || 0;
=+    var selfCount = selfHist[key] || 0,
=+        otherCount = otherHist[key] || 0;

**Comment by 3y3** [comment]
Which is your node version?

**Comment by 3y3** [comment]
Ignore my previous comment.
Reasonable. Will be fixed ASAP.

**Comment by 3y3** [comment]
Fixed in 5.3.2
