### ISSUE TITLE
The process exit after profiling the CPU

### ISSUE THREAD

**Issue by jfromaniello** [node-inspector/v8-profiler#82]
I am using node 1.8.4 

Is this normal?

**Comment by jfromaniello** [comment]
It happens when I call `profile.delete()`

**Comment by jfromaniello** [comment]
More info, this works:

```javascript
  profile.export()
    .pipe(fs.createWriteStream(file_name))
    .on('finish', function () {
      profile.delete();
    })
```

while this exit the process:

```javascript
  profile.export()
    .pipe(fs.createWriteStream(file_name))
    .on('finish', profile.delete)
```

**Comment by 3y3** [comment]
@jfromaniello , thank you for info. I'll inspect this issue ASAP

**Comment by 3y3** [comment]
My misstake in readme. Calling `.on('finish', profile.delete)` is incorrect.
I fix readme.
