### ISSUE TITLE
Does not build under Node v6.0.0

### ISSUE THREAD

**Issue by RobertWHurst** [node-inspector/v8-profiler#89]
<img width="1075" alt="screen shot 2016-04-26 at 7 45 39 pm" src="https://cloud.githubusercontent.com/assets/178857/14840268/8568909c-0be7-11e6-825b-33a84d405c07.png">

Just updated to Node v6.0.0. It seems I can no longer install node-inspector because v8-profiler is failing to build against the new V8.

**Comment by njbraun** [comment]
+1

**Comment by evanlucas** [comment]
This should be fixable by bumping to the latest nan version.

**Comment by RobertWHurst** [comment]
Should be fixed now that my PR has been merged :)

**Comment by RobertWHurst** [comment]
@3y3 Can you do a release to NPM?

**Comment by 3y3** [comment]
In progress

**Comment by RobertWHurst** [comment]
@3y3 🍻

**Comment by RobertWHurst** [comment]
@3y3 I've got a PR for node-inspector so let me know once you've published :)

**Comment by 3y3** [comment]
I should also update `v8-debug` deps
v8-profiler will be published after this build https://ci.appveyor.com/project/3y3/v8-profiler

**Comment by RobertWHurst** [comment]
@3y3 Okie dokie.

**Comment by 3y3** [comment]
@RobertWHurst ,v8-profiler 5.6.1 was published.
Thank you for fast fix!

(v8-debug is next in line)
